FROM nginx:latest
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./assets/ /usr/share/nginx/html/assets/
COPY ./app.js /usr/share/nginx/html/app.js
COPY ./index.html /usr/share/nginx/html/index.html
